name: callEcho method
description: callEcho method via composite actions
inputs:
  arg1:
    description: arg1
    required: true
    default: "hello"
  arg2:
    description: arg2
    required: true
    default: "world"
runs:
  using: "composite"
  steps:
    - name: Runs echo arg1
      run: echo ${{ inputs.arg1 }}
      shell: bash
    - name: Runs echo arg2
      run: echo ${{ inputs.arg2 }}
      shell: bash
    - name: greetMe('arin')
      id: greet1
      uses: ./.github/actions/greet-me
      with:
        name: "arin"
    - name: greetMe()
      id: greet2
      uses: ./.github/actions/greet-me
    - name: output1
      run: echo output 1 is ${{ steps.greet1.outputs.result }}
      shell: bash
    - name: output2
      run: echo output 2 is ${{ steps.greet2.outputs.result }}
      shell: bash
