name: greetMe method
description: greetMe method via composite actions
inputs:
  name:
    description: name
    required: true
    default: "test"
outputs:
  random-number:
    description: random number
    value: ${{ steps.return-value.outputs.result }}
runs:
  using: "composite"
  steps:
    - name: Runs echo name
      run: echo ${{ inputs.name }}
      shell: bash
    - name: return value
      id: return-value
      run: echo "result=true" >> $GITHUB_OUTPUT
      shell: bash
