name: greetMe method
description: greetMe method via composite actions
inputs:
  name:
    description: name
    required: true
    default: "test"
outputs:
  random-number:
    description: random number
    value: ${{ steps.random-number-generator.outputs.value }}
runs:
  using: "composite"
  steps:
    - name: Runs echo name
      run: echo ${{ inputs.name }}
      shell: bash
    - name: return
      id: random-number-generator
      run: echo "random-number=$(echo $RANDOM)" >> $GITHUB_OUTPUT
      shell: bash
