name: greetMe method
description: greetMe method via composite actions
inputs:
  name:
    description: name
    required: true
    default: "test"
outputs:
  return-value:
    description: random number
    value: ${{ steps.return-value.outputs.return-value }}
runs:
  using: "composite"
  steps:
    - name: Runs echo name
      run: echo ${{ inputs.name }}
      shell: bash
    - id: return-value
      run: |
        if [ "${{ inputs.name }}" != "test" ]; then
          echo "return-value=true" >> $GITHUB_OUTPUT;
        else
          echo "return-value=false" >> $GITHUB_OUTPUT;
        fi
      shell: bash
