name: arin/simple_method_call
on:
  workflow_dispatch:
jobs:
  Untitled_1:
    name: Untitled_1
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.5.0
    - uses: "./.github/actions/callecho"
      with:
        arg1: hello
        arg2: world
