name: play with status checks 
on:
  workflow_dispatch:
jobs:
  Untitled_1:
    name: Untitled_1
    runs-on: ubuntu-latest
    steps:
    - name: Fails
      run: exit 1
    - name: Does not run
      run: echo "this should not display"
    - name: Should run despite failure
      run: echo "this should display despite previous failure"
      if: ${{ !cancelled() }}
    - name: Should this be displayed? 
      run: echo "not sure"
