name: arin/simple_method_call
on:
  workflow_dispatch:
jobs:
  Untitled_1:
    name: Untitled_1
    runs-on: ubuntu-latest
    steps:
    - name: Fails
      run: exit 1
      id: step-1
    - name: Does not run
      run: echo 
      id: step-2
    - name: Should run despite failure
      run: echo "this should display despite previous failure"
      if: ${{ !cancelled() }}
      id: step-3
    - name: Should this be displayed? 
      run: echo ${{ steps.step-3.outcome }}
      id: step-4
